---
title: "Teaching"
editor: visual
---

# Teaching Program: Implementation and Content

## Implementation

Implementation phase goes through the Spring Semester 2022 up to Spring Semester 2025 (total of 3 years). During this phase, there will be implementation of 36 (108 hours) lectures and 36 (108 hours) seminars given by the project team.

The main objective of the methodological approach(es) employed in teaching activities is to provide a greater theoretical appreciation of the changing nature of regionalism and importance of inter-regional and trans-regional relations in EU studies. To this end, the project team will conduct both an analytical and conceptual investigation of the issue and develop a conceptual and historical approach to the study of EU's inter-regional and trans-regional relations. Our teaching will focus on the following research topics: - definition of inter-regionalism and trans-regionalism - theories and approaches of inter-regionalism and trans-regionalism, - causes and outcomes of inter-regionalism and trans-regionalism, - different cases of inter-regionalism and trans-regionalism - analysis of EU's inter-regionalism and trans-regionalism with different cases.

## Topics/themes of the Teaching Program

### Topic/Theme 1:

**Title:** Regionalism and EU **Prof. in charge:** Prof. Erhan Dogan **Description:** This course is an introductory course on the phenomenon of regionalism by taking the EU as both reference case study for regional cooperation and as an international policy actor strengthening multi-layered multilateral cooperation. The lecture starts with the fact that globalization and regionalism are now not only economic but also multidimensional and political processes. In this sense, to understand the role of the EU in this new environment, we have to go beyond classical approaches and understanding of regionalism.

1.  Regionalism: A conceptual Framework
2.  Theoretical Discussions on Regionalism I: Classic Theories
3.  Theoretical Discussions on Regionalism II: Critical Theories
4.  EU as a Regional Integration I: 1945-1990
5.  EU as a Regional Integration II: 1990-2008
6.  EU as a Regional Integration III: What lies Ahead?

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 2:

**Title:** Inter-regionalism

**Prof. in charge:** Assoc. Prof. Hakan Mehmetcik

**Description:** This lecture is an introductory course on the concept of inter-regionalism and brief cases of inter-regional relations in world politics. The lecture takes EU and its inter-regional relations as its focus of study.

1.  Inter-regionalism, Trans-regionalism and Cross-regionalism: A conceptual Framework
2.  Analysis of ASEM , 3. Analysis of FEALAC
3.  Analysis of Euro Mediterranean Partnership
4.  Analysis of EU and African Union 6. Analysis of EU and MERCOSUR Relations.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 3:

**Title:** International Trade and Trans-regionalism

**Prof. in charge:** Prof. Ali Arı

**Description:** This lecture is an introductory lecture on international trade and the phenomenon of trans-regionalism by taking the EU as a particular case.

1.  Contemporary international trade
2.  Main institutions and actors
3.  Multilateralism in international trade
4.  Rise of minilateralism
5.  Rise of rising powers
6.  EU and trans-regionalism.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 4:

**Title:** Inter-regional Relations between EU and Asia: ASEM and Beyond

**Prof. in charge:** Assoc. Prof. Hakan Mehmetcik

**Description:** EU's relations with ASEAN is not straight and smooth even though it is the oldest dialog partnership for ASEAN. This lecture is an introductory lecture on EU's inter-regional relations with ASEAN, which is institutionalized as ASEM. During the course of the lecture, other inter-regional dialogue such as ARF and APEC will also be analysed and compared to ASEM in terms of their structure, outcomes and future risks and possibilities.

1.  EU's economic relations with Asia
2.  EU's political and security relations with Asia
3.  ASEAN as an Asian regional organization
4.  EU and ASEAN partnership: ASEM
5.  Other institutions and actors
6.  APEC, ARF and ASEM: Similarities and Differences.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 5:

**Title:** EU-BRICS-MIKTA

**Prof. in charge:** Prof. Emel Parlar Dal

**Description:** This lecture is an introductory lecture on the growing relations between EU and other groupings of rising powers, namely BRICS and MIKTA. The role of these informal groups has been increasing since the 2008 financial crisis. Especially, studying these groups and their effects on the global economy and global governance via G20, and UN has become one of the most important dynamics in international politics. This lecture will analyse EU's policy with regard to BRICS and MIKTA by taking G20 and UN as an operational ground.

1.  What is BRICS? 2. What is MIKTA?
2.  What types of roles BRICS and MIKTA play in global governance?
3.  What are the similarities and differences between these groups?
4.  EU's policy options
5.  Comparison of EU'S policy in G20 with BRICS and MIKTA
6.  Comparison of EU'S policy in UN with BRICS and MIKTA.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 6:

**Title:** Inter-regional Relations between EU and North and Latin America

**Prof. in charge:** Assoc. Prof. Hakan Mehmetcik

**Description:** This lecture is an introductory lecture on inter-regional relations between EU and North America. Euro-Atlantic relations are historically very important and institutionalized one even though there are rifts and problems between the US and some EU countries. The recent EU-Canada FTAs is also important in this sense. However, there are very little, if there is at all, inter-regional relations between the EU and NAFTA (UMSCA). That also derives from the fact that NAFTA and EU is totally different phase of regionalism (one is a regional FTA while the other is a full-regional-integration). However, this is very different when it comes to EU and Latin American Relations. European Union Member States and the Latin American countries committed themselves to reinforcing the existing strategic partnership between the European Union and Latin America. Thus, this lecture will cover both EU's relations with individual North American countries (Mexico, Canada but not the US since it is dealt with another lecture in this series) and EU's interregional relations with Latin America. The focus will be on the later.

1.  EU's Transatlantic Relations: Dynamics and Evolution
2.  Comprehensive Economic and Trade Agreement (CETA): Why is it important?
3.  What happened to the Transatlantic Trade and Investment Partnership?
4.  Historical evolution of regionalisms in Latin America and the Caribbean
5.  EU and Central America
6.  EU and Andean Community
7.  EU and CARICOM 8. EU and MERCOSUR
8.  EU and CELAC.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 7:

**Title:** Inter-regional Relations in Eurasia

**Prof. in charge:** Assoc. Prof. Hakan Mehmetcik

**Description:** This lecture is an introductory lecture on EU's inter-regional relations with Eurasian ROs including the new emerging Chinese Belt and Road Initiatives. Eurasia is a fertile ground for geo-political rivalry not just in terms of security and politics but also trade and regionalism. In this sense, there are three rival visions of regionalism that have an effect on regional outlooks in Eurasia. The first one, the Russian led regionalism institutionalized under Eurasian Economic Union, and CSS. The second one is EU's aspirational regionalism that can be found aspirations of the countries for joining the EU. The last and recent one is China led Belt and Road Initiative. Thus, in this regional dynamics, the EU does not just conduct inter-regional relations but also actively rivals those ROs. This lecture provides a fresh perspective to analyse the actors, dynamics and outputs of EU's inter-regional relations in Eurasia.

1.  Eurasia: Theory and Practice of Regional Integration
2.  Regionalism and Energy Politics in Eurasia
3.  Regionalism and Great Powers in Eurasia
4.  EU's role as a ROs in fostering cooperation and competition
5.  EU's inter-regional Relations: EU and EEU
6.  Individual EU countries and Chinese BRI.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 8:

**Title:** Trans-regional Relations between EU and USA

**Prof. in charge:** Assoc. Prof. İmran Demir

**Description:** This lecture is an introductory lecture on the EU and the USA trans-regional relations. There is a historical context, especially in terms of security through NATO, of the EU's transatlantic relations with the USA. The trade is also an important dynamic. However, there are strong indicators of changing these dynamics, which brings us to question of the relationship. In that sense, this lecture deals with many of the contemporary side of the EU and US trans-regional relations. Areas of economic cooperation and tension will be studied, including the financial crisis, international trade and regulatory affairs, and the failed negotiation of a transatlantic trade and investment partnership.  The course will also take up cooperative and conflicting policies of transatlantic partners in addressing security problems of terrorism, failed states, refugees and human rights catastrophes. The lecture will also focus on the EU, US and UK relations in the post-Brexit era.

1.  The history of the EU and US relations
2.  The trade diplomacy of trans-Atlantic relations
3.  The role of the United States and the European Union in foreign affairs, and the overall aims of US and EU foreign policy: Security and Broader external and Foreign Relations
4.  The Technology and Environmental aspects of trans-Atlantic relations
5.  Opportunities and challenges lies ahead in the trans-Atlantic relations
6.  The US-EU and UK relations in the post-Brexit period: The implications of Brexit for future UK, US, and EU foreign policy.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 9:

**Title:** Trans-regional Relations between EU and China

**Prof. in charge:** Prof. Çağdaş Üngör Sunar

**Description:** This lecture is an introductory lecture on EU's trans-regional relations with China. The EU and China have a deep and comprehensive partnership over many different areas and Sino-European relations have become one of the most important relations over the last decade with growing trans-regional relations in many different subjects from security to technology.

1.  The Sino-European Relations: A historical Background
2.  New challenges, new opportunities, new approaches in Sino-European Relations
3.  The trade relations between EU and China
4.  The high politics: A shared Multilateralism Perspective
5.  Mapping Chinese Investment in Europe and evaluating its impact
6.  China, a strategic partner or a rival? 7. EU's national security and Chinese technological upper hand.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 10:

**Title:** Inter-regional Relations between EU and Africa

**Prof. in charge:** Assoc. Prof. Hakan Mehmetcik

**Description:** This lecture is an introductory lecture on EU's relations with Ros in Africa. The first and most important African Ros, is African Union. The EU has very substantial relations with African Union and many other sub-regional organizations from trade to peacekeeping missions. Africa is a very important continent with a huge potential. Rise of the rising powers is also an important strategic issue that affects the EU's core strategies toward Africa. In this sense, EU's inter-regional relations have to be comprehensively studied in the current environment. To this end, this lecture provides tools and readings for EU's inter-regional relations with African ROs.

1.  Conceptualizing Regionalism in Africa
2.  Main ROs in Africa 3. Inter-regionalism between Europe and Africa: EU and African Union Relations
3.  Inter-regionalism between Europe and Africa: EU and African Sub-Regional Organizations
4.  Quasi-Inter-regionalism and role of Non-State Actors
5.  Assessing EU-Africa inter-regionalism: What lies in the Future.

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 11:

**Title:** Trans-regional Relations between EU and Russia

**Prof. in charge:** Assoc. Prof. Emre Ersen

**Description:** This lecture is an introductory lecture on EU's trans-regional relations with Russia. This course examines major issues in EU.-Russian relations, including views on sovereignty, values, and world order; Eastern Europe, the Middle East, and East Asia; and nuclear weapons, cyber, and each country's role in the other's domestic politics.

1.  The EU and Russia Relations: A historical overview
2.  The security dynamics in the post-Crimea/post-Ukraine conflicts era
3.  The broader external and Foreign Relations
4.  The Energy Security dynamics in EU and Russia Relations
5.  The trade issues 6. Strategic Freeze of Strategic Partnership: Diverging Individual Perceptions on Russia
6.  What lies ahead in EU-Russian Relations after Russian Invasion of Ukraine

[A Detailed Content & Reading List](drive.google.com)

### Topic/Theme 11:

**Title:** Trans-regional Relations between EU and Turkey

**Prof. in charge:** Assoc. Prof. Hakan Mehmetcik

**Description:** This lecture is an introductory lecture on the EU's trans-regional relations with Turkey.

1.  The EU and Turkey Relations: A historical Background
2.  The trade relations between Turkey and EU
3.  The Security dynamics between Turkey and EU
4.  The Syrian Civil War and Migration Issue
5.  The EU-Turkish Relations since 2002: The beginning of the End?
6.  Diplomatic Stalemate: How far can it go?
7.  The future of the EU-Turkey Relations.

[A Detailed Content & Reading List](drive.google.com)
